version: '3.8'

services:

  website:
    restart: unless-stopped
    build: .
    env_file:
      - .env

  proxy:
    image: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config

#volumes: